### ISSUE TITLE
Sync API

### ISSUE THREAD

**Issue by raine** [watson/stackman#3]
This module looks like just what I need (getting context for the nearest call site outside by lib) but being async makes it inapplicable to my use case where I'm wrapping synchronous functions with the possibility of them throwing an error (in which case I'd like to show context around the callsites).

**Comment by watson** [comment]
@raine the reason why it's async is because it's reading the source-files from disk using `fs.readFile`. Wouldn't it bother you to use `fs.readFileSync`? That would degrade performance of the rest of your application.

**Comment by raine** [comment]
Valid point, however my library is used for debugging purposes so performance is not a concern.

**Comment by watson** [comment]
@raine Makes sense - I'll look into making a sync version

**Comment by watson** [comment]
@raine you can now add a `sync` option when initializing stackman:

```js
var stackman = require('stackman')({ sync: true })

var err = new Error('boom')

var stack = stackman(err)

stack.frames.forEach(function (frame) {
  // ...
})
```

Let me know what you think - especially if you find any issues with it
